global:
route:
  receiver: Default
  group_by: ['alertname']
  group_wait:      15s
  group_interval:  15s
  repeat_interval: 1m  

  routes:     
  - receiver: AlertaDataBase
    match:
      team: mongodb
    continue: true         

  - receiver: AlertaWebApi
    match:
      team: webapi   

receivers:
- name: Default
  webhook_configs:
  - url: 'https://pruu.herokuapp.com/dump/wpwebhookdefault'         
- name: AlertaDataBase
  slack_configs:
  - api_url: https://hooks.slack.com/services/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  
    channel: '#monitoramento-mongodb'
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    text: "\nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"         
  webhook_configs:
  - url: 'https://pruu.herokuapp.com/dump/wpwebhookmongodb'

- name: AlertaWebApi
  webhook_configs:
  - url: 'https://pruu.herokuapp.com/dump/wpwebhookwebapi'    