apiVersion: v1
kind: Service
metadata:
  name: mongodb-service  
spec:
  selector:
    app: mongodb-deploy
  ports:
  - port: 27017
    targetPort: 27017
  - port: 9216
    targetPort: 9216
  type: LoadBalancer
