apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-azurefile
  namespace: monitoramento  
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi